// src/components/caucus/CaucusForm.vue
<template>
  <div>
    <ion-item>
      <ion-input
        label="Caucus Topic"
        label-placement="stacked"
        :value="topic"
        @ion-input="$emit('update:topic', ($event.target as HTMLIonInputElement).value)"
      />
    </ion-item>

    <ion-item v-if="caucusType !== CaucusType.GSL">
      <ion-input
        label="Caucus Time (seconds)"
        label-placement="stacked"
        type="number"
        :value="initialCaucusTime"
        @ion-input="$emit('update:initialCaucusTime', Number(($event.target as HTMLIonInputElement).value))"
      />
      <p style="color: var(--ion-color-medium); font-size: 0.85em; padding-top: 4px;">
        This will reset the remaining caucus time to this value.
      </p>
    </ion-item>

    <ion-item v-if="caucusType !== CaucusType.UNMODERATED">
      <ion-input
        label="Speaker Time (seconds)"
        label-placement="stacked"
        type="number"
        :value="initialSpeakerTime"
        @ion-input="$emit('update:initialSpeakerTime', Number(($event.target as HTMLIonInputElement).value))"
      />
    </ion-item>
  </div>
</template>

<script setup lang="ts">
import type { CaucusType } from "@/models/Caucus";
import { IonInput, IonItem } from "@ionic/vue";

defineProps<{
	topic: string;
	initialSpeakerTime: number;
	initialCaucusTime: number;
	caucusType: CaucusType;
}>();

defineEmits<{
	"update:topic": [value: string];
	"update:initialSpeakerTime": [value: number];
	"update:initialCaucusTime": [value: number];
}>();
</script>

// src/components/caucus/CaucusFormComponent.tsx
import type { Observable } from "@legendapp/state";
import { View } from "react-native";
import { Input } from "~/components/ui/input";
import { Label } from "~/components/ui/label";
import { Muted } from "~/components/ui/typography";
import { type Caucus, CaucusType } from "~/lib/caucus/Caucus";

export default function CaucusForm({
	state,
}: {
	state: Observable<
		Pick<Caucus, "topic" | "initialSpeakerTime" | "initialCaucusTime" | "type">
	>;
}) {
	return (
		<View className="flex gap-y-4">
			<View>
				<Label>Caucus Topic</Label>
				<Input
					defaultValue={state.topic.get()}
					onChangeText={state.topic.set}
				/>
			</View>
			{state.type.get() !== CaucusType.GSL && (
				<View>
					<Label>Caucus Time (seconds)</Label>
					<Muted className="mb-2">
						This will reset the remaining caucus time to this value.
					</Muted>
					<Input
						keyboardType="numeric"
						defaultValue={state.initialCaucusTime.get()?.toString()}
						onChangeText={(v) =>
							state.initialCaucusTime.set(Number.parseInt(v))
						}
					/>
				</View>
			)}
			{state.type.get() !== CaucusType.UNMODERATED && (
				<View>
					<Label>Speaker Time (seconds)</Label>
					<Input
						keyboardType="numeric"
						defaultValue={state.initialSpeakerTime.get()?.toString()}
						onChangeText={(v) =>
							state.initialSpeakerTime.set(Number.parseInt(v))
						}
					/>
				</View>
			)}
		</View>
	);
}
